# Module 2 Assignment 1

### Exercise 1: Create a title using a Markdown Cell

 # Exploring Jupyter Notebook Features (this is the title)


### Exercise 2: Add an Introduction using Markdown

(Introduction)In this notebook, we will:
- Create and manipulate a pandas DataFrame
- Perform operations with numpy arrays
- Practice using Markdown, Code, and Raw cells

### Exercise 3: Insert a Code Cell to create a pandas DataFrame

- Use this dictionary to create a Pndas dataframe and then show the dataframe in the next cell.

```python
data = {
    "Product": ["Phone", "Laptop", "Tablet"],
    "Price": [699, 1200, 450],
    "Stock": [50, 30, 20],
}

In [96]:
import pandas as pd #type:ignore
data = {
    "Product": ["Phone", "Laptop", "Tablet"],
    "Price": [699, 1200, 450],
    "Stock": [50, 30, 20],
}

df = pd.DataFrame(data)
print(df)

  Product  Price  Stock
0   Phone    699     50
1  Laptop   1200     30
2  Tablet    450     20


### Exercise 4: Add a Code Cell to perform the following operations with Numpy

In [97]:
import numpy as np # type: ignore
elements = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(elements)
print(f"Sum of elements: {np.sum(elements)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of elements: 45


### Exercise 5: Create a Series 

In [98]:
import pandas as pd # type: ignore
import numpy as np # type: ignore
fruits = pd.Series(['apple', 'banana', 'cherry', 'date'])
print(fruits)

0     apple
1    banana
2    cherry
3      date
dtype: object


### Exercise 6: Create a DataFrame from a CSV file

- Load 'netherlands_IT_salaries.xlsx' file into a Pandas DataFrame and answer the following questions (file in Datasets folder on Microsoft Teams):
    - Print the number of rows and columns in the DataFrame.
    - Create and print a list of column names.
    - Display the first five rows of the DataFrame.
    - Display the last five rows of the DataFrame.

In [99]:
# TODO
import pandas as pd

salaries = pd.read_excel("netherlands_IT_salaries.xlsx")
print(f"Number of rows: {len(salaries.index)}")
print(f"Number of columns: {len(salaries.columns)}")
print(f"Column names: {list(salaries.columns)}")



Number of rows: 1134
Number of columns: 7
Column names: ['Year', 'Age', 'Role', 'City', 'Education', 'Experience', 'Salary']


In [100]:
salaries.head(5)

Year  Age                 Role       City Education  Experience  Salary
0  2018   47      Helpdeskmanager  Apeldoorn       HBO        25.0  4950.0
1  2018   42  Applicatiebeheerder     Almelo      HAVO        10.0  4086.0
2  2018   42        BI Consultant        NaN       MBO        25.0  4400.0
3  2018   39    Software Engineer  Amsterdam       MBO         6.0  3600.0
4  2018   38        IT Consultant     Mierlo       HBO        15.0  4900.0

In [101]:
salaries.tail(5)

Year  Age                  Role      City Education  Experience  Salary
1129  2021   23        Data Scientist  Randstad        WO         0.0  3750.0
1130  2021   23  System Administrator    Arnhem       MBO         0.0  2375.0
1131  2021   22     Software Engineer   Hengelo       HBO         0.0  2850.0
1132  2021   22     Software Engineer    Arnhem       HBO         0.0  2500.0
1133  2021   21     Software Engineer     Breda       MBO         1.0  2385.0

### Exercise 7: Explore the Data

- Do the following operations on the dataframe:
    - Display the summary statistics of the DataFrame. (DataFrame method)
    - Display the data types of the DataFrame. (DataFrame attribute)
    - Display the number of non-null values in each column. (DataFrame method)
    - Display the unique values in the 'Education' column. (Series method)
    - Display the number of unique values in the 'Education' column. (Series method)
    - Display the number of unique values in the DataFrame. (DataFrame method)

In [102]:
salaries.describe()

Year          Age   Experience        Salary
count  1134.000000  1134.000000  1130.000000   1101.000000
mean   2019.586420    29.182540     5.519469   3511.183470
std       0.899657     5.098952     4.959899   1282.149202
min    2018.000000    18.000000     0.000000      2.000000
25%    2019.000000    25.000000     2.000000   2650.000000
50%    2020.000000    28.000000     4.000000   3250.000000
75%    2020.000000    32.000000     8.000000   4100.000000
max    2021.000000    53.000000    30.000000  11137.000000

In [103]:
salaries.dtypes

Year            int64
Age             int64
Role           object
City           object
Education      object
Experience    float64
Salary        float64
dtype: object

In [104]:
salaries.count()

Year          1134
Age           1134
Role          1134
City           877
Education     1070
Experience    1130
Salary        1101
dtype: int64

In [105]:
salaries["Education"].unique()

array(['HBO', 'HAVO', 'MBO', 'WO', nan, 'HIO', 'VWO', 'Mavo', 'MBOo 3',
       'VMBO', 'Havo', 'HBO, WO', 'B', 'ul', 'IT'], dtype=object)

In [106]:
salaries.nunique()

Year            4
Age            36
Role          171
City          136
Education      14
Experience     27
Salary        390
dtype: int64

## Methods for Series and DataFrame

- You should already noticed that some methods are only available for Series, while others are only available for DataFrames. 

  For example, the nunique() method is only available for Series, while the describe() method is only available for DataFrames. 

- But there are also some methods that are available for both Series and DataFrames. 

  For example, the unique() method is available for both Series and DataFrames.

### Exercise 8: More Attributes and Methods of Sries and Dataframe

- Try to learn more about the attributes and methods of Series and DataFrame object which can be used to explore the data and try to apply some of them to the DataFrame you have already created from the given file.
- Use them and create markdown cells to explain what they are for.

In [107]:
salaries.groupby('Education')['Salary'].mean().sort_values(ascending=False)

Education
HIO        4950.000000
Mavo       4700.000000
B          4300.000000
VWO        4215.363636
HAVO       4155.000000
WO         4070.546448
HBO        3539.434286
MBOo 3     3240.000000
HBO, WO    3150.000000
ul         3100.000000
MBO        3062.391447
Havo       2966.666667
VMBO       2100.000000
IT                 NaN
Name: Salary, dtype: float64

In [108]:
salaries.groupby('Experience').agg({
    'Salary': ['mean', 'median', 'count', 'std']
}).round(2)

Salary                       
               mean  median count      std
Experience                                
0.0         2608.12  2587.5   110   528.63
1.0         2657.26  2700.0   127   768.77
2.0         2961.87  2859.0   135   764.91
3.0         3131.94  3075.0   118   754.10
4.0         3393.43  3250.0    95   967.99
5.0         3615.15  3400.0   100  1019.71
6.0         3681.96  3509.5    70  1224.63
7.0         3935.10  3750.0    49  1076.67
8.0         4078.65  4000.0    48  1330.98
9.0         4252.06  4100.0    31  1191.89
10.0        4157.27  3867.0    45  1327.55
11.0        4341.81  4272.0    31  1232.44
12.0        4430.06  4400.0    33  1217.42
13.0        5157.88  4852.0    17  1811.35
14.0        4512.64  4421.5    14  1383.93
15.0        5107.00  5150.0    19  1398.81
16.0        5120.14  4962.5    14  1930.69
17.0        4342.22  4300.0     9  1021.05
18.0        3880.00  3860.0     4   923.18
19.0        5688.40  4417.0     5  2353.64
20.0        5458.91  4800.0    11  2040.82
21.0        6512.33  5500.0     3  4210.78
22.0        4545.00  4545.0     2   487.90
25.0        4942.50  4675.0     4  1669.10
27.0        4500.00  4500.0     1      NaN
28.0        6500.00  6500.0     1      NaN
30.0        7100.00  7100.0     1      NaN